In [1]:
import pandas as pd
df=pd.read_csv('Airport.csv')

In [2]:
df.head()

,PASSENGERS,FREIGHT,MAIL,DISTANCE,UNIQUE_CARRIER,AIRLINE_ID,UNIQUE_CARRIER_NAME,UNIQUE_CARRIER_ENTITY,REGION,CARRIER,...,DEST_CITY_NAME,DEST_STATE_ABR,DEST_STATE_FIPS,DEST_STATE_NM,DEST_WAC,YEAR,QUARTER,MONTH,DISTANCE_GROUP,CLASS
0,0,NaN,0,24,YV,20378,Mesa Airlines Inc.,6689,D,YV,...,"Houston, TX",TX,48,Texas,74,2025,1,1,1,F
1,0,NaN,0,141,YV,20378,Mesa Airlines Inc.,6689,D,YV,...,"Hayden, CO",CO,8,Colorado,82,2025,1,1,1,F
2,0,NaN,0,152,YV,20378,Mesa Airlines Inc.,6689,D,YV,...,"Gunnison, CO",CO,8,Colorado,82,2025,1,1,1,F
3,0,NaN,0,156,YV,20378,Mesa Airlines Inc.,6689,D,YV,...,"Wichita, KS",KS,20,Kansas,62,2025,1,1,1,F
4,0,NaN,0,167,YV,20378,Mesa Airlines Inc.,6689,D,YV,...,"Austin, TX",TX,48,Texas,74,2025,1,1,1,F

In [3]:
df.describe()

,PASSENGERS,FREIGHT,MAIL,DISTANCE,AIRLINE_ID,CARRIER_GROUP,CARRIER_GROUP_NEW,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,...,ORIGIN_WAC,DEST_AIRPORT_ID,DEST_AIRPORT_SEQ_ID,DEST_CITY_MARKET_ID,DEST_STATE_FIPS,DEST_WAC,YEAR,QUARTER,MONTH,DISTANCE_GROUP
count,19926.000000,1.972100e+04,1.992600e+04,19926.000000,19926.000000,19926.000000,19926.000000,19926.000000,1.992600e+04,19926.000000,...,19926.000000,19926.000000,1.992600e+04,19926.000000,19926.000000,19926.000000,19926.0,19926.0,19926.0,19926.000000
mean,3041.422814,9.323393e+04,7.789142e+03,804.673944,20287.599317,2.520526,3.111713,12804.345177,1.280438e+06,32089.064940,...,49.017063,12797.244806,1.279728e+06,32083.027452,25.449614,49.012195,2025.0,1.0,1.0,2.148951
std,6049.405124,7.162761e+05,8.572336e+04,670.125075,683.915171,0.742646,1.012874,1576.655653,1.576654e+05,1492.111295,...,29.355060,1575.724840,1.575724e+05,1488.765011,17.753501,29.337139,0.0,0.0,0.0,1.325816
min,0.000000,0.000000e+00,0.000000e+00,0.000000,19393.000000,0.000000,0.000000,10011.000000,1.001104e+06,30007.000000,...,1.000000,10011.000000,1.001104e+06,30007.000000,1.000000,1.000000,2025.0,1.0,1.0,1.000000
25%,9.000000,0.000000e+00,0.000000e+00,299.250000,19874.000000,2.000000,3.000000,11298.000000,1.129806e+06,30849.000000,...,33.000000,11293.500000,1.129353e+06,30849.000000,8.000000,33.000000,2025.0,1.0,1.0,1.000000
50%,597.000000,0.000000e+00,0.000000e+00,644.500000,20304.000000,3.000000,3.000000,12892.000000,1.289208e+06,31703.000000,...,43.000000,12892.000000,1.289208e+06,31703.000000,24.000000,43.000000,2025.0,1.0,1.0,2.000000
75%,3443.750000,1.728000e+03,0.000000e+00,1089.000000,20422.000000,3.000000,3.000000,14107.000000,1.410702e+06,33195.000000,...,74.000000,14107.000000,1.410702e+06,33195.000000,41.000000,74.000000,2025.0,1.0,1.0,3.000000
max,81227.000000,5.177205e+07,4.192740e+06,5095.000000,22135.000000,3.000000,9.000000,17011.000000,1.701101e+06,36846.000000,...,93.000000,17011.000000,1.701101e+06,36846.000000,78.000000,93.000000,2025.0,1.0,1.0,11.000000

In [14]:
df.shape

(19926, 36)

In [4]:
#checking missing values

In [5]:
df.isnull().sum()

PASSENGERS                 0
FREIGHT                  205
MAIL                       0
DISTANCE                   0
UNIQUE_CARRIER             0
AIRLINE_ID                 0
UNIQUE_CARRIER_NAME        0
UNIQUE_CARRIER_ENTITY      0
REGION                     0
CARRIER                    0
CARRIER_NAME               0
CARRIER_GROUP              0
CARRIER_GROUP_NEW          0
ORIGIN_AIRPORT_ID          0
ORIGIN_AIRPORT_SEQ_ID      0
ORIGIN_CITY_MARKET_ID      0
ORIGIN                     0
ORIGIN_CITY_NAME           0
ORIGIN_STATE_ABR           0
ORIGIN_STATE_FIPS          0
ORIGIN_STATE_NM            0
ORIGIN_WAC                 0
DEST_AIRPORT_ID            0
DEST_AIRPORT_SEQ_ID        0
DEST_CITY_MARKET_ID        0
DEST                       0
DEST_CITY_NAME             0
DEST_STATE_ABR             0
DEST_STATE_FIPS            0
DEST_STATE_NM              0
DEST_WAC                   0
YEAR                       0
QUARTER                    0
MONTH                      0
DISTANCE_GROUP             0
CLASS                      0
dtype: int64

In [9]:
df['FREIGHT'].fillna(0)

0             0.0
1             0.0
2             0.0
3             0.0
4             0.0
           ...
19921    106071.0
19922     50103.0
19923     49120.0
19924    317524.0
19925     86122.0
Name: FREIGHT, Length: 19926, dtype: float64

In [10]:
df.isnull().sum()

PASSENGERS               0
FREIGHT                  0
MAIL                     0
DISTANCE                 0
UNIQUE_CARRIER           0
AIRLINE_ID               0
UNIQUE_CARRIER_NAME      0
UNIQUE_CARRIER_ENTITY    0
REGION                   0
CARRIER                  0
CARRIER_NAME             0
CARRIER_GROUP            0
CARRIER_GROUP_NEW        0
ORIGIN_AIRPORT_ID        0
ORIGIN_AIRPORT_SEQ_ID    0
ORIGIN_CITY_MARKET_ID    0
ORIGIN                   0
ORIGIN_CITY_NAME         0
ORIGIN_STATE_ABR         0
ORIGIN_STATE_FIPS        0
ORIGIN_STATE_NM          0
ORIGIN_WAC               0
DEST_AIRPORT_ID          0
DEST_AIRPORT_SEQ_ID      0
DEST_CITY_MARKET_ID      0
DEST                     0
DEST_CITY_NAME           0
DEST_STATE_ABR           0
DEST_STATE_FIPS          0
DEST_STATE_NM            0
DEST_WAC                 0
YEAR                     0
QUARTER                  0
MONTH                    0
DISTANCE_GROUP           0
CLASS                    0
dtype: int64

In [11]:
# Checking for duplicate rows
duplicates = df.duplicated().sum()
print("Number of duplicate rows:", duplicates)

Number of duplicate rows: 0

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19926 entries, 0 to 19925
Data columns (total 36 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   PASSENGERS             19926 non-null  int64
 1   FREIGHT                19926 non-null  float64
 2   MAIL                   19926 non-null  int64
 3   DISTANCE               19926 non-null  int64
 4   UNIQUE_CARRIER         19926 non-null  object
 5   AIRLINE_ID             19926 non-null  int64
 6   UNIQUE_CARRIER_NAME    19926 non-null  object
 7   UNIQUE_CARRIER_ENTITY  19926 non-null  object
 8   REGION                 19926 non-null  object
 9   CARRIER                19926 non-null  object
 10  CARRIER_NAME           19926 non-null  object
 11  CARRIER_GROUP          19926 non-null  int64
 12  CARRIER_GROUP_NEW      19926 non-null  int64
 13  ORIGIN_AIRPORT_ID      19926 non-null  int64
 14  ORIGIN_AIRPORT_SEQ_ID  19926 non-null  int64
 15  ORIGIN_CITY_MARKET_ID  19926 non-null  int64
 16  ORIGIN                 19926 non-null  object
 17  ORIGIN_CITY_NAME       19926 non-null  object
 18  ORIGIN_STATE_ABR       19926 non-null  object
 19  ORIGIN_STATE_FIPS      19926 non-null  int64
 20  ORIGIN_STATE_NM        19926 non-null  object
 21  ORIGIN_WAC             19926 non-null  int64
 22  DEST_AIRPORT_ID        19926 non-null  int64
 23  DEST_AIRPORT_SEQ_ID    19926 non-null  int64
 24  DEST_CITY_MARKET_ID    19926 non-null  int64
 25  DEST                   19926 non-null  object
 26  DEST_CITY_NAME         19926 non-null  object
 27  DEST_STATE_ABR         19926 non-null  object
 28  DEST_STATE_FIPS        19926 non-null  int64
 29  DEST_STATE_NM          19926 non-null  object
 30  DEST_WAC               19926 non-null  int64
 31  YEAR                   19926 non-null  int64
 32  QUARTER                19926 non-null  int64
 33  MONTH                  19926 non-null  int64
 34  DISTANCE_GROUP         19926 non-null  int64
 35  CLASS                  19926 non-null  object
dtypes: float64(1), int64(20), object(15)
memory usage: 5.5+ MB

In [15]:
df.head()

,PASSENGERS,FREIGHT,MAIL,DISTANCE,UNIQUE_CARRIER,AIRLINE_ID,UNIQUE_CARRIER_NAME,UNIQUE_CARRIER_ENTITY,REGION,CARRIER,...,DEST_CITY_NAME,DEST_STATE_ABR,DEST_STATE_FIPS,DEST_STATE_NM,DEST_WAC,YEAR,QUARTER,MONTH,DISTANCE_GROUP,CLASS
0,0,0.0,0,24,YV,20378,Mesa Airlines Inc.,6689,D,YV,...,"Houston, TX",TX,48,Texas,74,2025,1,1,1,F
1,0,0.0,0,141,YV,20378,Mesa Airlines Inc.,6689,D,YV,...,"Hayden, CO",CO,8,Colorado,82,2025,1,1,1,F
2,0,0.0,0,152,YV,20378,Mesa Airlines Inc.,6689,D,YV,...,"Gunnison, CO",CO,8,Colorado,82,2025,1,1,1,F
3,0,0.0,0,156,YV,20378,Mesa Airlines Inc.,6689,D,YV,...,"Wichita, KS",KS,20,Kansas,62,2025,1,1,1,F
4,0,0.0,0,167,YV,20378,Mesa Airlines Inc.,6689,D,YV,...,"Austin, TX",TX,48,Texas,74,2025,1,1,1,F

In [16]:
#connecting to mysql for analysis

In [17]:
pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in C:\Users\Praful\AppData\Local\Programs\Python\Python313\Lib\site-packages (9.5.0)
Note: you may need to restart the kernel to use updated packages.

In [18]:
pip install pymysql

Requirement already satisfied: pymysql in C:\Users\Praful\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.1.2)
Note: you may need to restart the kernel to use updated packages.

In [19]:
import mysql.connector

In [25]:
connection=mysql.connector.connect(
    host='localhost',
    user='root',
    password='Prafulsql4266',
    database='airport'
)

In [21]:
cursor=connection.cursor()

In [22]:
pip install sqlalchemy

Requirement already satisfied: sqlalchemy in C:\Users\Praful\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.0.48)
Requirement already satisfied: greenlet>=1 in C:\Users\Praful\AppData\Local\Programs\Python\Python313\Lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\Praful\AppData\Local\Programs\Python\Python313\Lib\site-packages (from sqlalchemy) (4.14.0)
Note: you may need to restart the kernel to use updated packages.

In [23]:
from sqlalchemy import create_engine

In [26]:
engine=create_engine('mysql+pymysql://root:Prafulsql4266@localhost/airport')

In [27]:
df.to_sql('customer_shopping_behaviour',engine,if_exists='replace',index=False)

19926